language: bash
dist: trusty
sudo: required
env:
  - OS=debian ARCH=amd64 DIST=jessie
  - OS=debian ARCH=amd64 DIST=stretch
  - OS=debian ARCH=amd64 DIST=buster
  - OS=ubuntu ARCH=amd64 DIST=trusty
  - OS=ubuntu ARCH=amd64 DIST=xenial
  - OS=ubuntu ARCH=amd64 DIST=bionic
cache:
  directories:
    - $HOME/cache

before_install:
  - sudo apt-add-repository ppa:ev3dev/tools --yes
  - sudo apt-get update
  - sudo apt-get install --yes --no-install-recommends
    dpkg-dev
    git-buildpackage
    pbuilder
    debootstrap
    debian-archive-keyring
    ev3dev-archive-keyring
    ev3dev-ppa-keyring
    raspbian-archive-keyring
    debhelper
    qemu-user-static
    pandoc
    fakeroot
  - mkdir -p $HOME/bin
  - ln -s $TRAVIS_BUILD_DIR/src/pbuilder-ev3dev.sh $HOME/bin/pbuilder-ev3dev
  - export PATH=$HOME/bin:$PATH

before_script:
  - git checkout -B master

script:
  - pbuilder-ev3dev base
  - pbuilder-ev3dev build
