language: bash
dist: trusty
sudo: required
env:
  - OS=debian ARCH=amd64 DIST=jessie
  - OS=debian ARCH=amd64 DIST=stretch
  - OS=ubuntu ARCH=amd64 DIST=trusty
  - OS=ubuntu ARCH=amd64 DIST=xenial
  - OS=ubuntu ARCH=amd64 DIST=bionic
cache:
  directories:
    - $HOME/cache

before_install:
  - sudo apt-add-repository ppa:ev3dev/tools --yes
  - sudo apt-get update
  - sudo apt-get install --yes --no-install-recommends
    dpkg-dev
    git-buildpackage
    pbuilder
    debootstrap
    debian-archive-keyring
    ev3dev-archive-keyring
    ev3dev-ppa-keyring
    raspbian-archive-keyring
    debhelper
    qemu-user-static
    pandoc
    fakeroot
  # temporary need for trusty-proposed
  - sudo cp .travis/trusty-proposed.list /etc/apt/sources.list.d/
  - sudo apt update
  - sudo apt install dpkg
  # end temporary workaround
  - mkdir -p $HOME/bin
  - ln -s $TRAVIS_BUILD_DIR/src/pbuilder-ev3dev.sh $HOME/bin/pbuilder-ev3dev
  - export PATH=$HOME/bin:$PATH
  - if [ ! -e /usr/share/debootstrap/scripts/bionic ]; then
      sudo ln -s gutsy /usr/share/debootstrap/scripts/bionic;
    fi

before_script:
  - git checkout -B ev3dev-trusty

script:
  - pbuilder-ev3dev base || sudo rm /home/travis/cache/base-$DIST-$ARCH.tgz
  - pbuilder-ev3dev build
